### ISSUE TITLE
Proctoring is missing...

### ISSUE THREAD

**Issue by holtmeier** [oat-sa/extension-tao-proctoring#334]
Hi,

I've a problem after updating proctoring-extension from 3.16.0 to 4.15.0.

It's gone. It doesn't show up in the menu anymore. And in extensions manager I can not activate proctoring again. It doesn't show up there, too.

I'm sure there is a simple solution. Can anybody help my please?

Best regards Stephan

**Comment by jbout** [comment]
Hi,
The way Proctoring 3.x and 4.x work are very different:

* Proctoring 3.x was centered around the concept of test-centers and test-taker preregistration.
* Proctoring 4.x focuses purely on the proctoring interface, independent on the assignment business logic.

If you require the old test-center management, you will either need to remain on the 3.x branch or use the https://github.com/oat-sa/extension-tao-testcenter/tree/refactor/split-testcenter-proctoring which is the branch we are currently migrating test-center functionalities to.

**Comment by holtmeier** [comment]
Hi jbout,
thanks! I've always updated to newer versions and tested them. Now, I ask myself how to downgrade. Can I simply change composer.json in the main directory? And what do I have to insert?

**Comment by jbout** [comment]
Take a look at https://getcomposer.org/doc/articles/versions.md#tilde

As explained there ~3.16 is equivalent to >=3.16 <4.0.0 so the line you are looking for is:

`"oat-sa/extension-lti-proctoring" : "~3.16",`

**Comment by holtmeier** [comment]
Hi jbout,

it worked for me. At least I couldn't recognize any suspicious behavior, so far.

Instead of 
"oat-sa/extension-lti-proctoring" : "~3.16",
I used
"oat-sa/extension-tao-proctoring": "~3.16",

Thanks again for your help and I'll Close this issue now.

**Comment by jbout** [comment]
That was a typo, your line is correct.

Glad you got it working.
